-- Run after schema.sql
begin;
insert into public.participants (id,full_name,ic_passport,phone_number,email,project_name,unit_number,agent_name,created_at,has_spun) values ('P4Fgnos0IITKH0Z0n8jF','Sandra Teo ','930408145280','0162026048','sandrateo.property@gmail.com','Queenswoodz ','B-09-18','Sandra','2026-06-04T13:52:07.371Z',true) on conflict (id) do update set full_name=excluded.full_name,ic_passport=excluded.ic_passport,phone_number=excluded.phone_number,email=excluded.email,project_name=excluded.project_name,unit_number=excluded.unit_number,agent_name=excluded.agent_name,created_at=excluded.created_at,has_spun=excluded.has_spun;
insert into public.participants (id,full_name,ic_passport,phone_number,email,project_name,unit_number,agent_name,created_at,has_spun) values ('WxSNpbHPsjDpG3lInRB1','111','111','111','111@gmail.com','111','111','SANDRA TEO','2026-06-11T11:35:12.159Z',false) on conflict (id) do update set full_name=excluded.full_name,ic_passport=excluded.ic_passport,phone_number=excluded.phone_number,email=excluded.email,project_name=excluded.project_name,unit_number=excluded.unit_number,agent_name=excluded.agent_name,created_at=excluded.created_at,has_spun=excluded.has_spun;
insert into public.participants (id,full_name,ic_passport,phone_number,email,project_name,unit_number,agent_name,created_at,has_spun) values ('cQDduiUnf7qYfxKCZRmV','Vincent Ngoo','930408145234','0166684062','sandrateo@gmail.com','Queenswoodz ','B-08-08','Sandra Teo','2026-06-10T13:59:16.687Z',false) on conflict (id) do update set full_name=excluded.full_name,ic_passport=excluded.ic_passport,phone_number=excluded.phone_number,email=excluded.email,project_name=excluded.project_name,unit_number=excluded.unit_number,agent_name=excluded.agent_name,created_at=excluded.created_at,has_spun=excluded.has_spun;
insert into public.participants (id,full_name,ic_passport,phone_number,email,project_name,unit_number,agent_name,created_at,has_spun) values ('oTo4DDQL8arv271BkuZt','Teo Pui Pui ','940506061829','60145678904','teo.property@gmail.com','Viividz','A-09-09','Dino Chia','2026-06-11T03:54:10.071Z',true) on conflict (id) do update set full_name=excluded.full_name,ic_passport=excluded.ic_passport,phone_number=excluded.phone_number,email=excluded.email,project_name=excluded.project_name,unit_number=excluded.unit_number,agent_name=excluded.agent_name,created_at=excluded.created_at,has_spun=excluded.has_spun;
insert into public.prizes (id,name,probability,max_winners,current_winners,description,image_url,image_path) values ('MpoiXJoG9Brd21fhSZlP','Xiaomi Rice Cooker',10,5,0,'','','') on conflict (id) do update set name=excluded.name,probability=excluded.probability,max_winners=excluded.max_winners,current_winners=excluded.current_winners,description=excluded.description,image_url=excluded.image_url,image_path=excluded.image_path;
insert into public.prizes (id,name,probability,max_winners,current_winners,description,image_url,image_path) values ('mP83OT1u4ootyPS84fFS','DJI POCKET',0,3,3,'Historical prize migrated from Firebase','','') on conflict (id) do nothing;
insert into public.draw_results (id,participant_id,prize_id,prize_name,draw_date,reference_number,acknowledgement_signed,signature) values ('1uPZb5p40rS2bvbiB1Vl','P4Fgnos0IITKH0Z0n8jF','mP83OT1u4ootyPS84fFS','DJI POCKET','2026-06-04T13:52:18.247Z','LD-2026-0316',false,null) on conflict (id) do update set participant_id=excluded.participant_id,prize_id=excluded.prize_id,prize_name=excluded.prize_name,draw_date=excluded.draw_date,reference_number=excluded.reference_number,acknowledgement_signed=excluded.acknowledgement_signed,signature=excluded.signature;
insert into public.draw_results (id,participant_id,prize_id,prize_name,draw_date,reference_number,acknowledgement_signed,signature) values ('EYZGJupbocQBkSTTgUxg','oTo4DDQL8arv271BkuZt','mP83OT1u4ootyPS84fFS','DJI POCKET','2026-06-11T04:11:16.426Z','LD-2026-9325',false,null) on conflict (id) do update set participant_id=excluded.participant_id,prize_id=excluded.prize_id,prize_name=excluded.prize_name,draw_date=excluded.draw_date,reference_number=excluded.reference_number,acknowledgement_signed=excluded.acknowledgement_signed,signature=excluded.signature;
insert into public.draw_results (id,participant_id,prize_id,prize_name,draw_date,reference_number,acknowledgement_signed,signature) values ('UZfcHelOMCMshQycui1h','P4Fgnos0IITKH0Z0n8jF','mP83OT1u4ootyPS84fFS','DJI POCKET','2026-06-04T13:52:19.551Z','LD-2026-4506',false,null) on conflict (id) do update set participant_id=excluded.participant_id,prize_id=excluded.prize_id,prize_name=excluded.prize_name,draw_date=excluded.draw_date,reference_number=excluded.reference_number,acknowledgement_signed=excluded.acknowledgement_signed,signature=excluded.signature;
insert into public.settings (key,value) values ('formFields','{"showUnit":true,"showAgent":true,"showProject":true,"showPhone":true,"showIC":true,"showEmail":true}'::jsonb) on conflict (key) do update set value=excluded.value,updated_at=now();
commit;
